AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (SO8135)
  geo_traffic_blocker

  Block requests from specific country

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GeoTrafficBlockerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: geo_traffic_blocker/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GeoTrafficBlockerFunction:
    Description: "GeoTrafficBlockerFunctionRole ARN"
    Value: !GetAtt GeoTrafficBlockerFunction.Arn
  GeoTrafficBlockerFunctionIamRole:
    Description: "Implicit IAM Role created for GeoTrafficBlockerFunction function"
    Value: !GetAtt GeoTrafficBlockerFunctionRole.Arn
  SolutionId:
    Description: "Solution id"
    Value: "SO8135"   
